name: publish

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - LICENSE
      - SECURITY.md
      - '.github/**'
      - Makefile
      - contributing.md
      - .gitignore
      - working-group-charter.md
      
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - LICENSE
      - SECURITY.md
      - '.github/**'
      - Makefile
      - contributing.md
      - .gitignore
      - working-group-charter.md

jobs:
  build-pushpull:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install kramdown-rfc
        run: gem install kramdown-rfc
      - name: Install xml2rfc
        run: pip install xml2rfc
      - name: Convert pushpull md to xml
        run: kramdown-rfc2629 draft-tulshibagwale-saag-pushpull-delivery.md > draft-tulshibagwale-saag-pushpull-delivery.xml
      - name: Render HTML
        run: xml2rfc draft-tulshibagwale-saag-pushpull-delivery.xml --html -o index.html
      - name: Render Text
        run: xml2rfc draft-tulshibagwale-saag-pushpull-delivery.xml --text
      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-pushpull
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
